version: "3.9"
services:
  web:
    image: shuvoasl/ccl_invoice_backend_web
    ports:
      - "${APP_PORT}:8000"
    command: >
      sh -c "python manage.py makemigrations invoice &&
              python manage.py makemigrations
             python manage.py migrate invoice &&
             python manage.py migrate &&
              python manage.py test && python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    restart: unless-stopped
  
  redis:
    image: redis
  
  celery_worker:
    restart: always
    image: shuvoasl/ccl_invoice_backend_celery_worker
    command: celery -A main worker -l info
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  
  celery_beat_schedular:
    restart: always
    image: shuvoasl/ccl_invoice_backend_celery_beat_schedular
    command: celery -A main beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
volumes:
  postgres_data:
  pgadmin_data: